In [1]:
import pandas as pd
df=pd.read_csv('retail_sales.csv')
df

,product_id,product_name,category,brand,seller,seller_city,price,discount_percent,final_price,rating,...,weight_g,warranty_months,color,size,return_policy_days,is_returnable,payment_modes,shipping_weight_g,product_score,seller_rating
0,FKP0000001,Adidas Ultra 664,Toys,Adidas,MegaStore,Hyderabad,35547.34,15,30215.24,1.9,...,3038.23,36,Green,XL,30,True,"COD,CARD",3483.592454,6.78,3.28
1,FKP0000002,LG Series 124,Fashion,LG,ValueKart,Mumbai,30693.79,10,27624.41,3.2,...,1921.82,0,Grey,One Size,7,True,"UPI,CARD",2091.473835,50.78,3.42
2,FKP0000003,Redmi Model 35,Beauty,Redmi,SmartDeals,Ahmedabad,51214.50,40,30728.70,4.4,...,1143.49,12,Black,M,0,False,"COD,UPI,CARD",1242.770494,4.24,4.23
3,FKP0000004,Sony Edition 769,Toys,Sony,UrbanRetails,Delhi,33168.49,30,23217.94,2.8,...,3644.81,24,Black,L,0,False,"CARD,Wallet",3891.222716,1.38,3.45
4,FKP0000005,Boat Prime 291,Home & Kitchen,Boat,RetailHub,Pune,14181.34,0,14181.34,3.7,...,310.33,0,Blue,NaN,30,True,"CARD,Wallet",386.061014,79.27,4.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,FKP0079996,Prestige Ultra 500,Sports,Prestige,MegaStore,Kolkata,42928.63,5,40782.20,1.1,...,3069.10,0,Gold,One Size,10,True,"UPI,CARD",3273.175933,20.07,4.88
79996,FKP0079997,Sony Prime 225,Mobiles,Sony,QuickShop,Ahmedabad,20158.55,10,18142.70,3.8,...,4412.53,0,Blue,M,30,True,"COD,CARD",5452.722633,6.97,4.57
79997,FKP0079998,LG Series 545,Beauty,LG,UrbanRetails,Kolkata,25317.70,20,20254.16,4.7,...,3114.32,0,Blue,S,7,True,"COD,UPI,CARD",3500.625634,1.28,4.15
79998,FKP0079999,Reebok Model 744,Toys,Reebok,MegaStore,Kolkata,7414.51,40,4448.71,4.3,...,3496.17,24,Gold,XL,30,True,"CARD,Wallet",3940.607738,5.06,3.63
79999,FKP0080000,Puma Ultra 650,Home & Kitchen,Puma,ValueKart,Kolkata,55472.95,30,38831.06,3.8,...,1858.88,6,Green,M,30,True,"CARD,Wallet",2082.266179,72.66,3.87

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          80000 non-null  object
 1   product_name        80000 non-null  object
 2   category            80000 non-null  object
 3   brand               80000 non-null  object
 4   seller              80000 non-null  object
 5   seller_city         80000 non-null  object
 6   price               80000 non-null  float64
 7   discount_percent    80000 non-null  int64
 8   final_price         80000 non-null  float64
 9   rating              80000 non-null  float64
 10  review_count        80000 non-null  int64
 11  stock_available     80000 non-null  int64
 12  units_sold          80000 non-null  int64
 13  listing_date        80000 non-null  object
 14  delivery_days       80000 non-null  int64
 15  weight_g            80000 non-null  float64
 16  warranty_months     80000 non-null  int64
 17  color               80000 non-null  object
 18  size                66516 non-null  object
 19  return_policy_days  80000 non-null  int64
 20  is_returnable       80000 non-null  bool
 21  payment_modes       80000 non-null  object
 22  shipping_weight_g   80000 non-null  float64
 23  product_score       80000 non-null  float64
 24  seller_rating       80000 non-null  float64
dtypes: bool(1), float64(7), int64(7), object(10)
memory usage: 14.7+ MB

In [3]:
df.describe()

,price,discount_percent,final_price,rating,review_count,stock_available,units_sold,delivery_days,weight_g,warranty_months,return_policy_days,shipping_weight_g,product_score,seller_rating
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.00000,80000.000000,80000.000000,80000.000000,80000.000000
mean,30137.256454,21.350625,23697.780600,2.999671,25102.249875,499.194262,2507.515775,6.006325,2522.224622,15.56400,12.362250,2899.960047,50.673750,4.002218
std,17274.048682,16.354446,14726.821259,1.156238,14428.769942,288.917706,1439.519972,3.160630,1428.287966,12.91307,10.019794,1650.921766,28.562732,0.577595
min,200.140000,0.000000,101.080000,1.000000,0.000000,0.000000,0.000000,1.000000,50.020000,0.00000,0.000000,53.155250,1.000000,3.000000
25%,15180.205000,10.000000,11341.722500,2.000000,12605.000000,249.000000,1261.000000,3.000000,1283.117500,6.00000,7.000000,1469.583781,25.950000,3.500000
50%,30164.455000,20.000000,22571.265000,3.000000,25166.500000,499.000000,2513.000000,6.000000,2524.550000,12.00000,10.000000,2892.632502,50.670000,4.010000
75%,45077.087500,40.000000,34521.057500,4.000000,37666.000000,749.000000,3754.000000,9.000000,3753.195000,24.00000,15.000000,4304.695597,75.430000,4.500000
max,59995.800000,50.000000,59995.800000,5.000000,49999.000000,999.000000,4999.000000,11.000000,4999.920000,36.00000,30.000000,6234.757448,100.000000,5.000000

In [4]:
print(df['brand'].head())

0    Adidas
1        LG
2     Redmi
3      Sony
4      Boat
Name: brand, dtype: object

In [5]:
expensive_items=df[df['final_price']>20000]
print(expensive_items)

       product_id        product_name        category     brand        seller  \
0      FKP0000001    Adidas Ultra 664            Toys    Adidas     MegaStore
1      FKP0000002       LG Series 124         Fashion        LG     ValueKart
2      FKP0000003      Redmi Model 35          Beauty     Redmi    SmartDeals
3      FKP0000004    Sony Edition 769            Toys      Sony  UrbanRetails
9      FKP0000010   Philips Prime 114     Electronics   Philips       BestBuy
...           ...                 ...             ...       ...           ...
79989  FKP0079990        HP Prime 413            Toys        HP  UrbanRetails
79994  FKP0079995       HP Series 332          Sports        HP  UrbanRetails
79995  FKP0079996  Prestige Ultra 500          Sports  Prestige     MegaStore
79997  FKP0079998       LG Series 545          Beauty        LG  UrbanRetails
79999  FKP0080000      Puma Ultra 650  Home & Kitchen      Puma     ValueKart

      seller_city     price  discount_percent  final_price  rating  ...  \
0       Hyderabad  35547.34                15     30215.24     1.9  ...
1          Mumbai  30693.79                10     27624.41     3.2  ...
2       Ahmedabad  51214.50                40     30728.70     4.4  ...
3           Delhi  33168.49                30     23217.94     2.8  ...
9       Bengaluru  53392.85                15     45383.92     4.5  ...
...           ...       ...               ...          ...     ...  ...
79989   Ahmedabad  57809.75                 5     54919.26     3.5  ...
79994   Hyderabad  34012.98                15     28911.03     3.2  ...
79995     Kolkata  42928.63                 5     40782.20     1.1  ...
79997     Kolkata  25317.70                20     20254.16     4.7  ...
79999     Kolkata  55472.95                30     38831.06     3.8  ...

       weight_g  warranty_months  color      size  return_policy_days  \
0       3038.23               36  Green        XL                  30
1       1921.82                0   Grey  One Size                   7
2       1143.49               12  Black         M                   0
3       3644.81               24  Black         L                   0
9        288.08               36  Green         S                  10
...         ...              ...    ...       ...                 ...
79989    683.61                6   Grey         S                   7
79994   1501.65                6  White  One Size                   7
79995   3069.10                0   Gold  One Size                  10
79997   3114.32                0   Blue         S                   7
79999   1858.88                6  Green         M                  30

       is_returnable  payment_modes shipping_weight_g product_score  \
0               True       COD,CARD       3483.592454          6.78
1               True       UPI,CARD       2091.473835         50.78
2              False   COD,UPI,CARD       1242.770494          4.24
3              False    CARD,Wallet       3891.222716          1.38
9               True       UPI,CARD        355.641359         64.93
...              ...            ...               ...           ...
79989           True       COD,CARD        803.230153         66.14
79994           True    CARD,Wallet       1758.789240         74.56
79995           True       UPI,CARD       3273.175933         20.07
79997           True   COD,UPI,CARD       3500.625634          1.28
79999           True    CARD,Wallet       2082.266179         72.66

       seller_rating
0               3.28
1               3.42
2               4.23
3               3.45
9               4.66
...              ...
79989           3.42
79994           3.64
79995           4.88
79997           4.15
79999           3.87

[44511 rows x 25 columns]

In [6]:
result=df.groupby('brand').agg(
    total_products=('brand', 'count'),
    avg_price=('final_price', 'mean')
).reset_index
print(result)

<bound method DataFrame.reset_index of            total_products     avg_price
brand
Adidas               5281  23914.919316
Apple                5389  23752.201932
Boat                 5258  24032.806723
Dell                 5341  23691.538996
HP                   5297  23636.539579
LG                   5345  23439.006935
Nike                 5358  23725.595931
Philips              5340  23587.247208
Prestige             5401  23684.781605
Puma                 5409  23890.778109
Redmi                5340  23649.429577
Reebok               5387  23485.492647
Samsung              5345  23690.865935
Sony                 5287  23692.622676
Whirlpool            5222  23596.830417>

In [7]:
filtered_result=(
    df[df['final_price']>2000]
    .groupby('brand')
    .agg(
        total_products=('brand','count'),
        avg_price=('final_price', 'mean')
    )
    .reset_index()
    .sort_values(by='avg_price',ascending=False)
)
print(filtered_result)

        brand  total_products     avg_price
2        Boat            5061  24925.632703
0      Adidas            5063  24900.008977
1       Apple            5149  24810.870212
9        Puma            5205  24784.699266
13       Sony            5058  24715.671870
10      Redmi            5100  24712.058831
12    Samsung            5121  24680.080340
6        Nike            5152  24629.863271
14  Whirlpool            4993  24628.360054
8    Prestige            5194  24586.463057
4          HP            5084  24583.040858
3        Dell            5139  24578.180996
7     Philips            5121  24551.075329
5          LG            5098  24526.934298
11     Reebok            5167  24439.961842

In [16]:
import numpy as np
df_filtered=df[(df['category']== 'Fashion') & (df['stock_available']>5)].copy()
df_filtered['price_tier']= np.where(df_filtered['final_price']>2000, 'High Price', 'Low Price')

result_tier=(
    df_filtered.groupby(['brand', 'price_tier'])
    .agg(
        total_items=('brand', 'count'),
        avg_price=('final_price', 'mean')
    )
    .reset_index()
    .sort_values(by='total_items', ascending=False)
)
print(result_tier)

        brand  price_tier  total_items     avg_price
16   Prestige  High Price          694  24941.663228
22     Reebok  High Price          688  24531.425654
18       Puma  High Price          676  25100.884527
26       Sony  High Price          659  24679.544947
4        Boat  High Price          651  25231.375469
20      Redmi  High Price          648  25126.752886
0      Adidas  High Price          647  24006.578609
8          HP  High Price          639  24999.280110
6        Dell  High Price          633  23807.428325
28  Whirlpool  High Price          626  24464.356885
14    Philips  High Price          626  24606.876166
12       Nike  High Price          623  25162.456501
24    Samsung  High Price          622  23617.968489
2       Apple  High Price          608  25554.277286
10         LG  High Price          558  25129.647097
11         LG   Low Price           41    916.833415
1      Adidas   Low Price           37    904.097838
19       Puma   Low Price           33   1129.682424
21      Redmi   Low Price           31   1134.376774
27       Sony   Low Price           30   1065.380000
25    Samsung   Low Price           30   1106.044667
3       Apple   Low Price           29   1147.050345
29  Whirlpool   Low Price           25   1110.718000
5        Boat   Low Price           25   1050.782400
7        Dell   Low Price           23   1113.622609
13       Nike   Low Price           23   1141.570000
9          HP   Low Price           22   1054.113182
17   Prestige   Low Price           22   1179.727727
23     Reebok   Low Price           22   1115.320000
15    Philips   Low Price           19    872.973684